# Generated by Django 2.1.7 on 2019-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='London',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(max_length=200)),
                ('coleccion', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(max_length=200)),
                ('coleccion', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(max_length=200)),
                ('coleccion', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
