# Generated by Django 2.1.7 on 2019-03-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paris',
        ),
        migrations.DeleteModel(
            name='Pisa',
        ),
        migrations.RenameField(
            model_name='london',
            old_name='coleccion',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='london',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='london',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='london',
            name='paginas',
        ),
    ]
