# Generated by Django 2.1.7 on 2019-03-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_paris_pisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='london',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='paris',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pisa',
            old_name='name',
            new_name='nombre',
        ),
    ]
